# Generated by Django 5.0.6 on 2024-06-06 17:02

import django.db.models.deletion
from django.db import migrations, models, transaction

from ..models import Category


@transaction.atomic
def insert_default_category(apps, schema_editor):
    default_category = Category(name='Other')
    default_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_category_good_category'),
    ]

    operations = [
        migrations.RunPython(insert_default_category),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
