# Generated by Django 5.0.6 on 2024-06-06 17:02

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.db import migrations, models, transaction

from django.contrib.auth.models import User


@transaction.atomic
def insert_default_category(apps, schema_editor):
    password = '123456'
    hashed_password = make_password(password)
    default_user = User(username="StandarUser", password=hashed_password, email="bhobrus@gmail.com", is_staff=True, is_superuser=True)
    default_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_data_migration'),
    ]

    operations = [
        migrations.RunPython(insert_default_category),
    ]
